# Generated by Django 4.1.5 on 2023-01-08 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='manytomany3foreignkey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleforeignkey', models.CharField(default='', max_length=80, verbose_name='Title')),
            ],
        ),
        migrations.CreateModel(
            name='manytomany3manytomany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titlemanytomany', models.CharField(default='', max_length=80, verbose_name='Title')),
            ],
        ),
        migrations.CreateModel(
            name='manytomany3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(default='', max_length=80, verbose_name='Title')),
                ('title2', models.CharField(default='', max_length=80, verbose_name='Title2')),
                ('foreignkey_link', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.manytomany3foreignkey')),
                ('manytomany_link', models.ManyToManyField(blank=True, default=None, null=True, to='app.manytomany3manytomany')),
            ],
        ),
    ]
